---
title: Derechos Humanos
author: Lucas Fernandez
---


# Derechos Humanos


# 1. Conceptos Fundamentales

- Derechos Humanos

    Derechos Humanos son un conjunto de derechos considerados como esenciales
    para la dignidad humana, basadas en las ideas de libertad, igualdad y
    seguridad.

- Derechos Esenciales

    La CPR art. 5.2 utiliza el término "derechos esenciales que emanan de la
    naturaleza humana". En el plano internacional la Declaración de los
    Derechos y Deberes del Hombre 48 (Declaración de Bagota) se refiere en su
    preámbulo a "derechos esenciales del hombre".

    - ¿por qué existe esa imprecisión terminológica?

	Esto se debe a que la fundamentación de los derechos humanos esta
	concebida como derechos naturales, aquellos inherentes a la naturaleza
	humana. Dicha terminología se ha abierto a la constatación de la
	historicidad de cada uno de los derechos, siendo considerados, hoy en
	día, como verdaderos derechos conquistados.

- Derechos Fundamentales

    Los derechos fundamentales consisten en los derechos esenciales reconocidos
    y positivados en el plano interno en especial por la CPR.

    - Qué diferencia existe entre el término Derechos Humanos y Derechos
      Fundamentales?

	Se ha considerado que el término Derechos Humanos se refiere a los
	derechos esenciales reconocidos y garantizados por el Derecho
	Internacional, es decir, tanto en los tratados como en las demás normas
	internacionales (DIDH y DIH).

    - Cuál sería el propósito de diferenciar Derechos Humanos y Derechos
      Fundamentales?

	Se trata de diferenciar debido a la concepción de que los Derechos
	Humanos no serían siempre exigibles internamente por su matriz
	internacional. Los Derechos Fundamentales, dada su positivación interna
	serían posibles de exigibilidad judicial, por su matriz constitucional.

	Sin embargo, hoy en día dicha diferenciación no tiene mucha relevancia,
	dado que con el avance del DIDH los derechos consagrados en TI pueden
	ser igualmente exigibles tanto en el plano internacional como interno.

- Concepto Amplio de Derechos

    Consiste en 3 concepciones:

    1. Como **norma jurídica** que confiere derechos.
    2. Como **necesidades** **reconocidas** o que **reclamadas** terminan
       configurándose en norma.
    3. Como **reconocimiento de una realidad**, dotando **un mecanismo de
       garantía**.

- Concepto de Humano (F)

    Concepto basado en el pensamiento de Kant.

- Estado

    Se refiere al aparato estatal, como **sistema de instituciones**.

- Violencia

    Medio de sumisión o destrucción para alcanzar objetivos

- Protección

    Mecanismos para evitar la violación o vulneración de derechos

- Garantías

    Mecanismos para permitir que se consiga un derecho o para evitar su
    violación.

- Violación

    Sometimiento y destrucción total de un derecho o persona.

- Vulneración

    Situación de hecho que afecta a sujetos y que además supone una
    transgresión de una norma que consagra dicho derecho.

- Promoción

    Consiste en acciones positivas para conseguir o garantizar un derecho o
    situación.

- Necesidades

    Situación material de carencia de bienes, servicios, redes, estructuras o
    protección de derechos.

- Integralidad (característica de los DD.HH.)

    Todos los derechos reconocidos deben aplicarse y no unos excluir a otros.

- Universalidad (característica de los DD.HH.)

    Carácter **erga omnes**, aplicables a todos las personas

- Carta o Catálogo

    Son los Tratados o Declaraciones que contienen derechos humanos

- Positivación

    Acción de poner un derecho por escrito, transformándolo en una norma
    jurídica.

- reivindicaciones

    Solicitud de hacer efectivas soluciones a necesidades que terminan
    constituyéndose en derechos.

- Reclamaciones

    Consiste en la petición de cumplir derechos reconocidos

- Conquistas

    Derechos que tras luchas de demandas de soluciones o respeto resultan
    victoriosas y se logran obtener o escribir, positivandolo.

- Momentos básicos de la actuación del Estado sobre los DD.HH.

    Prevención, Castigo, Reparación.

# 2. Fuentes de los Derechos Humanos

- Fuentes Doctrinales
    - Escuela Iusnaturalista

	Consiste en una corriente del pensamiento jurídico que defiende la
	existencia de un conjunto de normas vinculantes anteriores y superiores
	al sistema de normas fijadas por el Estado en su ordenamiento positivo.

    - Escuela del Iusnaturalismo Contractualista

	Escuela que tiene por fundamento que la razón es la fuente de los
	derechos inherentes del humano, dando preeminencia de los derechos
	individuales frente al Estado. Esta preeminencia de derechos está dada
	por el contrato social que impone su protección y limita al Estado. En
	esta etapa los derechos humanos son considerados como *atemporales,
	inherentes a la naturaleza del hombre*. Se manifiesta en la DUDH,
	Locke, y Rousseau en el *contrato social*.

- Fuentes Internacionales

    Son fuentes internacionales los Tratados, Pactos o Convenciones
    Internacionales, las Declaraciones Internacionales.

- Fuentes Nacionales

    La CPR, leyes, jurisprudencia, los informes, las políticas públicas
    sectoriales  (Buscar el estatuto jurídico de cada uno y su exigibilidad).

# 3. Características o Principios Generales de los Derechos Humanos

- ¿Cuales son las Características de los DD.HH.?
    - Intrínsecos

	DUDH 48 o Declaración de París art. 1, dispone que basta la condición
	humana para ser titular de los derechos esenciales. Consiste en la
	calidad de pertenencia de estos derechos a todos los miembros de la
	especie humana, sin ninguna distinción.

    - Universales

	Los DD.HH. son atribuidos a todos los seres humanos, **erga omnes**,
	sin distinción alguna, como nacionalidad, u opción política,
	orientación sexual, creencia u otra. Afirmada en la DUDH 48, y
	continuamente reafirmado como en la Proclama de Teherán en el marco de la
	1ª Conferencia Mundial de los DD.HH. de la ONU 68, en la Declaración de
	Viena 93 en el marco de la 2ª Conferencia Mundial de los DD.HH. de la
	ONU.

    - Internacionales

	Está vinculado con el principio de universalidad, siendo una
	herramienta para la concreción de la universalidad de los derechos
	humanos que su protección sea una cuestión internacional en defecto de
	la protección nacional. De esta característica también se afirma que
	los DD.HH. deben ser considerados como *trasnacionales*, es decir, que
	no dependan del reconocimiento por parte de un Estado, o del vínculo de
	nacionalidad, existiendo un deber internacional de protección como en
	el caso de los refugiados o apátridas.

    - Indivisibles

	Consiste en que todos los derechos humanos deben tener la misma
	protección jurídica, dado que todos ellos son esenciales para la vida
	digna. Tiene dos facetas, una de que los DD.HH. protegidos constituyen
	una unidad en si, y la otra, de que no se debe proteger solamente
	algunos derechos reconocidos.

    - Interdependientes e Interrelacionados

	Consiste en el reconocimiento que todos los DD.HH. contribuyen,
	interactuando unos con los otros y sin excluirse, para la realización
	de la dignidad humana. Se señala también, derivado de este principio
	que los DD.HH. constituyen una *unidad* en el sentido de que la
	violación de un derecho compromete y vulnera los demás.

	- ¿En qué Instrumentos Internacionales se afirman las características
	  de Indivisibilidad e Interdependencia de los DD.HH.?

	    En la Declaración de Teherán 68, luego en la Declaración sobre el
	    Derecho al Desarrollo 86, en la Declaración de Viena 93.

    - Igualitarios

	Señala la Declaración de Viena 93 párr. 5ª que la comunidad
	internacional debe tratar a los DD.HH. de forma *global, justa y
	equitativa*.

    - Inagotables

	Se dice que los derechos humanos, debido a su historicidad y
	progresividad no son posibles de limitarlos a un numero taxativo sino
	que son inagotables y se van conquistando a lo largo de la historia.
	Manifestación de este principio característica se encuentra en la CPR
	art. 5.2 señalando que la soberanía tiene como limitación los derechos
	esenciales que emanan de la naturaleza humana y es deber deber de los
	órganos del Estado respetar y promover tales derechos, garantizados por
	la CPR como por los TI ratificados y vigentes.

    - Imprescriptibles

	Implica reconocer que los DD.HH. no se pierden con el paso del tiempo.

    - Inalienables

	No pueden ser atribuidos a una dimensión pecuniaria por la que se
	puedan disponer.

    - Indisponibles o Irrenunciables

	Las personas no pueden ceder o renunciar su titularidad en la condición
	humana para permitir la violación de estos derechos.

    - Qué se entiende por la "protección de intangibilidad" de los DD.HH.?

	Se refieren a las características de imprescribilidad, inalienabilidad,
	e indisponibilidad en conjunto, no consiste en un valor absoluto sino
	que se encuentran constantemente en ponderación con otros DD.HH. los
	cuales sirven como limitación, para los cuales se tendrán en
	consideración de la naturaleza de dichos derechos en contraposición y
	los valores sociales relevantes en una sociedad democrática.

    - Irreversibles o Prohibición de Retroceso

	Es un carácter fundamental por cuanto que una vez que el Estado lo haya
	reconocido a través de un tratado internacional o por la CPR solamente
	los asegura y garantiza reconociendo su valor inherente a las personas
	por lo que no pudiera dejar de serlo por decisión gubernamental.

	Los DD.HH. también se caracterizan por la existencia de la prohibición
	de retroceso de una conquista  ya alcanzada en la protección de algún
	derecho permitiendo solamente su  perfeccionamiento o mejoramiento.

    - Progresivos

	Los DD.HH. están en constante evolución a través de los diversos
	tratados y convenciones ampliando el ámbito del derecho y sus
	garantías. De esta forma en el plano internacional se ha desarrollado
	el principio de la "**integralidad maximizadora del sistema**" de
	manera que el DIDH está incorporando al derecho interno como fuente
	cuando contiene un plus y viceversa.

    - Absolutos

	Si bien es cierto que existe una teoría que señala que los derechos
	fundamentales jamás son absolutos dado que siempre deben ser ponderados
	con los demás derechos fundamentales (dado que ni uno ni otro implica
	una superioridad), existe un cierto consenso en decir que existen
	derechos humanos que si bien pudiesen ser entendidos como principios
	ellos operan como reglas, tal como sería la prohibición a la
	esclavitud, es decir, derechos que no aceptan ningún tipo de
	ponderación.

# 4. Clasificación de los Derechos Humanos

- Teoría de los Estatus - Jellinek

    Se trata de una teoría de los derechos constitucionales del siglo XIX en
    repudio de su autor a las teorías iusnaturalistas. Concibe que los DD.HH
    deben ser positivados en normas jurídicas estatales para que puedan ser
    garantizados y concretizados. Se caracteriza por el carácter positivo de
    los derechos y en la verticalidad de la relación entre individuo y Estado.
    Dado lo anterior el individuo puede encontrarse en 4 situaciones frente al
    Estado:

    - Estatus pasivo o de sumisión

	El Estado tiene atribuciones para vincular al individuo y exigir
	determinadas conductas e imponer prohibiciones, estableciendo deberes
	para contribuir al bien común.

    - Estatus negativo o de libertad

	Un conjunto de limitaciones a la acción del Estado para asegurar una
	dimensión subjetiva en su vida privada, impone un deber de abstención
	al Estado

    - Estatus positivo o civil

	Un conjunto de pretensiones del individuo para invocar la actuación del
	Estado para garantizar sus derechos

    - Estatus activo

	Conjunto de prerrogativas y facultades que tiene el individuo para
	participar en la formación de la voluntad del Estado que se refleja en
	el ejercicio de derechos políticos.

- Teoría de las Generaciones o Dimensiones - Vasak

    De 1979 por el jurista francés de origen checa una Conferencia en el
    Instituto Internacional de los Derechos Humanos en Estrasburgo fue tomada
    de los enunciados de la revolución francesa "libertad, igualdad y
    fraternidad" se clasifican por generaciones:

    - 1ª generación

	Derechos de la libertad (igualdad ante la ley, propiedad, seguridad),
	imponen prestaciones negativas en que el Estado debe proteger la esfera
	de autonomía del individuo. El rol del Estado en la defensa de los
	derechos de 1ª generación es tanto pasiva (absteniéndose de violar los
	DD.HH.) como activo, garantizando la seguridad pública, la
	administración de justicia

    - 2ª generación

	Son los derechos a la educación, salud, previsión social, vivienda. Los
	cuales exigen una prestación positiva por parte del Estado y están
	basados en la idea de igualdad

    - 3ª generación

	Son derechos que tienen por titulares a la comunidad, como lo son el
	derecho al desarrollo, a la paz, al derecho a la autodeterminación y al
	medio ambiente. Están basados en la idea de solidaridad (fraternidad)

    - Criticas a la teoría de Vasak
- Teoría de las Funciones
    - Derecho de defensa

	Conjunto de prerrogativas del individuo para defender determinadas
	posiciones subjetivas contra la intervención del Poder Público o de
	otro particular.

    - Derecho a prestación

	Son aquellos que exigen una obligación estatal de realizar una acción
	para asegurar la efectividad de los derecho humanos. Esta puede ser de
	prestación jurídica como lo es la elaboración de normas jurídicas que
	disciplinan la protección de un determinado derecho. Pueden ser también
	de prestación material, suministrando una determinada condición
	material para que el individuo pueda disfrutar adecuadamente de sus
	derechos.

    - Derecho a procedimientos e instituciones

	Son aquellos que tienen como función exigir del Estado que estructure
	órganos y cuerpos institucionales aptos, por su competencia y
	atribuciones a ofrecer bienes y servicios indispensables para el goce
	efectivo de los derechos humanos.

- Clasificación en cuanto a su finalidad
    - Derechos propiamente tales

	Se trata de las disposiciones normativas que miran al reconocimiento
	jurídico de las pretensiones inherentes a la dignidad del hombre.

    - Garantías fundamentales

	Buscan el goce efectivo de tales derechos. Estos pueden ser garantías
	en sentido amplio: conjunto de medios de índole institucional y
	orgánico que buscan la efectividad y observancia de los DD.HH. como
	podría ser el MP o el JG. Las garantías fundamentales en sentido
	estricto consisten en un conjunto de mecanismos procesales destinados a
	proteger los DD.HH.

- Clasificación según valores protegidos - Eusebio Fernandez

    Parte de la afirmación de que la dignidad humana deriva de los valores de
    seguridad-autonomía, la libertad, y la igualdad.

    - Valor seguridad-autonomía

	Da fundamento a los derechos personales y de seguridad individual y
	jurídica. Son los derechos a la vida, a la integridad física y
	psíquica, el derecho al honor y a la privacidad, libertad de conciencia
	y de culto, derecho a la igualdad ante la ley y la justicia, al debido
	proceso, a la libertad personal y seguridad individual, entre otros

- Clasificación según bien jurídico protegido en Chile
- Clasificación en cuando al desarrollo del DIDH según bienes protegidos
    - Derechos de carácter políticos
    - Derechos económicos, social y culturales
    - Derechos de los pueblos
    - Derechos de lo común

# 5. Limitaciones al Ejercicio o Goce de los DD.HH.

- Fundamentos jurídicos, bienes jurídicos y valores
- Limitaciones al Estado
- Estado de excepción, fuerza policial, garantías judiciales
- Limitaciones a los particulares
- Limitaciones a las empresas

- clasificación de las limitaciones a los dº fundamentales

    - limitaciones ordinarias y extraordinarias

	- ordinarias

	    son ordinarias aquellas que afectan el ejercicio de un derecho
	    tanto bajo condiciones de normalidad constitucional, como bajo
	    situaciones de excepción constitucional

	    + el ejercicio libre de todos los cultos reconoce como límite el
	      respeto por la **moral, las buenas costumbres y el orden
	      público**
	    + el ejercicio de la libertad de enseñanza queda sometido a la
	      moral, las buenas costumbres, el orden público y la **seguridad
	      nacional**
	    + derecho a reunirse si se ejerce pacíficamente, sin armas y en el
	      caso de reuniones en lugares públicos, **deberán respetarse las
	      disposiciones generales de la policía**

	- extraordinarias

	    son aquellas que se producen **sólo durante circunstancias de
	    emergencia social o institucional** y que han dado curso a la
	    *declaración de estados de excepción constitucional*. Art. 43 CPR

	    art. 27 CADH debe ser por el tiempo estrictamente limitado a las
	    exigencias de la situación, siempre que no sean incompatibles con
	    las demás obligaciones que les impone el derecho internacional y no
	    entrañen discriminación alguna fundada en motivos de raza, color,
	    sexo, idioma, religión, u origen social.

	    deberá cumplir con los requisitos de proclamación (actos de
	    publicación y publicidad en la determinación de responsabilidades
	    sobre las medidas excepcionales) y de notificación (informando de
	    manera inmediata a los demás Estados Parte de las disposiciones
	    cuya aplicación haya suspendido, sus motivos y fecha que haya dado
	    por terminada tal suspensión).

	    - **asamblea**
		- suspender o restringir la *libertad personal*
		- derecho de reunión
		- libertad de trabajo
		- restringir el derecho a asociación
		- interceptar, abrir o registrar documentos y toda clase de
		  comunicaciones
		- requisición de bienes
		- establecer limitaciones al derecho de propiedad

	    - **sitio**
		- restringir la libertad de locomoción
		- *arrestar* personas en su propia morada o lugares que la ley
		  determine y que no sean cárceles ni estén destinados a la
		  detención o prisión de reos comunes
		- suspender o restringir el ejercicio del derecho a reunión

	    - **catástrofe**
		- restringir las libertades de locomoción
		- reunión
		- requisición de bienes
		- establecer limitaciones al ejercicio del derecho de propiedad
		- adoptar medidas extraordinarias de carácter administrativo
		  que sean

	    - **emergencia**
		- restringir las libertades de locomoción
		- reunión

	Sin perjuicio de lo anterior, quedarán a salvo, siempre la garantía de
	recurrir ante las autoridades judiciales a través de los recursos que
	corresponda, y de indemnización respecto a afectaciones que se
	produzcan respecto al derecho de propiedad.


    - según origen de la limitación

	- respeto por los derechos fundamentales de los demás sujetos

	    impide a cada titular utilizar su derecho en perjuicio de otro, en
	    cumplimiento del bien común.

	    art. 32.2 CADH los derechos de cada persona están limitados por los
	    derechos de los demás, por la seguridad de todos y por las justas
	    exigencias del bien común en una sociedad democrática

	- límites de origen material o físico

	    dice relación con las reales posibilidades del Estado, directamente
	    o a través de las instituciones privadas que en virtud del
	    principio de subsidiaridad colaboran con el mismo fin. Se refieren
	    a los derechos de carácter prestacionales

	    PIDESC art. 2.1 cada Estado Parte en el presente Pacto se
	    compromete a adoptar, tanto por separado como mediante la
	    asistencia y la cooperación internacional, especialmente económicas
	    y técnicas, **hasta el máximo de los recursos de que disponga**,
	    para lograr progresivamente, por todos los medios apropiados,
	    inclusive en particular la adopción de medidas legislativas, la
	    plena efectividad de los derechos aquí reconocidos

	- limitaciones expresamente previstas por el ordenamiento jurídico
	  positivo

	    son aquellas que se encuentran en el ordenamiento jurídico mismo
	    por lo que, para invocarlas, basta con citar algún precepto
	    constitucional o legal para poder recurrir a ellas.

    - según norma en la que consta la limitación

	estas restricciones solo son válidas mientras sean constitucionales

	- restricciones directamente constitucionales

	    de rango constitucional y no existe delegación a otra autoridad o
	    persona para imponer tales limitaciones

	    - es el caso de las limitaciones a la libertad de culto, con la
	      moral, las buenas costumbres y el orden público
	    - los mismos límites respecto a libertad de enseñanza, agregando la
	      seguridad nacional
	    - la de proceder en términos respetuosos y convenientes en el caso
	      del derecho a la petición
	    - la moral, orden público y seguridad nacional en el caso de la
	      libertad de asociación

	- restricciones indirectamente constitucionales

	    son aquellas cuya imposición está autorizada por la CPR, generando
	    la competencia en favor de la ley u otro tipo de norma, para que
	    sean ellas las que impongan la limitación respectiva

	    en el caso de la CPR está el caso de la reserva legal, y en otros
	    casos se autoriza a autoridades administrativas e incluso jueces y
	    particulares.

	    - condiciones para la limitación indirecta

		Están sometidas a 2 circunstancias especiales: el contenido
		esencial de los derechos y la exigencia de justificación

		- condición respecto a su carácter de competencia

		    sólo podrán proceder a limitar un derecho fundamental
		    cuando previamente hayan sido habilitados
		    constitucionalmente para eso.

		    art. 6º supremacía constitucional

		    art. 19 Nº 26 preceptos legales podrán limitar las
		    garantías

		    Implica que el órgano estatal solo podrá limitar un derecho
		    fundamental cuando haya sido expresamente facultado para
		    ello.

		    sin embargo, hay casos excepcionales en que la limitación
		    puede venir de una norma de otro rango que no sea legal:

		    - derecho de las confesiones religiosas para erigir y
		      conservar templos y sus dependencias bajo las condiciones
		      de seguridad e higiene fijadas por leyes y **ordenanzas**
		    - derecho de reunión, cumpliendo las **disposiciones
		      generales de policía.**
		    - **jueces** están autorizados para limitar derechos en el
		      caso de que ordene allanamientos o interceptar, abrir o
		      registrar comunicaciones, o decretar la privación o
		      restricción de libertad en los casos y formas
		      establecidos por la CPR y las leyes
		    - el caso de los colegios profesionales (**personas
		      privadas**) están facultados para conocer las
		      reclamaciones que se interpongan sobre la conducta ética
		      de sus miembros, las cuales pueden establecer
		      restricciones a la libertad de trabajo

		- condición de carácter internacional

		    art.5º CPR todos los órganos se ven sometidos al deber de
		    ajustar su actuación al respecto de tales atributos
		    fundamentales, por lo que debe siempre considerar el
		    cumplimiento de las obligaciones internaciones contraídas
		    por el Estado.

		    + no podrá limitar un derecho cuya restricción esté
		      prohibida en el derecho internacional
		    + tampoco podrá hacerlo en hipótesis diferentes
		    + o en mayor medida
		    + o de un modo distinto al establecido en el derecho
		      internacional

		    art. 30 CADH

		    a) que se trate de una restricción expresamente autorizada
		    por la CADH, en las condiciones que ella lo haya permitido

		    b) para fines legítimos, razones de interés general y no se
		    aparten del propósito para el cual han sido establecidos

		    c) que estés dispuestas en leyes y se apliquen de
		    conformidad con ellas

		- condición de carácter material

		    se refiere al contenido esencial del derecho art. 19 Nº 26.
		    Consiste en una garantía frente al propio legislador.

		    según el TC es afectado en su esencia cuando le priva de
		    aquello que le es consustancial, de manera que deja de ser
		    reconocible

		- condición de carácter lógico

		    toda limitación debe estar justificada y justificada.

		    consiste en la aplicación del principio de
		    proporcionalidad.

    - limitaciones fácticas de los derechos

	todas aquellas restricciones a los derechos fundamentales de las
	personas que, si bien no cumplen con las condiciones que deben
	revestir, igualmente son establecidas o aceptadas como formalmente
	legítimas por los órganos de un Estado.

# 6. Rol del Estado en materia de DD.HH.

- Convención de Viena sobre el Derecho de los Tratados

    art. 26 Pacta sunt servanda, debe ser cumplido de buena fe

    art. 27. Eº Parte no podrá invocar disposiciones internas como
    justificación del incumplimiento de un tratado, salvo el caso del art. 46
    cuando se trate de una violación manifiesta (resulta objetivamente
    evidente) y afecte a una norma de importancia fundamental de su derecho
    interno

- CADH

    art. 1 Los Eº Parte se comprometen a respetar los derechos y libertades
    reconocidas y a garantizar su libre y pleno ejercicio, a toda persona bajo
    su jurisdicción, sin discriminación alguna

    art. 2 si el ejercicio no estuviere ya garantizado los Eº Parte se
    comprometen a adoptar, con arreglo a sus procedimientos para hacer
    efectivas tales derechos y libertades

- PIDCP

    art. 2 respetar y garantizar a todos los individuos que se encuentren en su
    territorio y sujetos a su jurisdicción, sin distinción alguna. Cada Eº se
    compromete a adoptar las medidas oportunas para hacer efectivos los
    derechos reconocidos en el presente pacto

- ¿cuándo se produce la responsabilidad internacional del Eº?


	Para establecer que se ha producido una violación de los derechos
	asegurados en un tratado internacional de derechos humanos basta con la
	demostración de que ha habido **apoyo o tolerancia** del poder público
	en la infracción de los derechos reconocidos.  El Estado puede ser
	responsable tanto por acción, omisión o negligencia.  Se genera de
	inmediato con el ilícito internacional, aunque sólo puede ser exigida
	después de que el Eº haya tenido la oportunidad de repararlo por sus
	propios medios.


- concepto de agente estatal

    tiene un contenido autónomo que es independiente de la organización formal
    y legal del derecho doméstico. Se incluye tanto los particulares en los que
    el Estado delegue poderes públicos y cualquiera otra persona que estén
    subordinadas de cualquier forma al Estado y ejecuten actos por orden de
    éste o con su tolerancia o aquiescencia

- Casos en que la violación es producto de particulares

	Un particular es una persona que no tiene vínculos ni de hecho ni de
	derecho con el Estado. En este caso puede producirse la responsabilidad
	por permitir, tolerar o apoyar indirectamente las acciones de los
	particulares. Una de las formas con la cual el Estado puede tolerar es
	**omitiendo su deber de investigación y sanción**.

- obligaciones estatales derivadas del DIDH

	Los tratados de derechos humanos si bien tienen una naturaleza distinta
	a los demás derechos humanos están sujetos a las mismas normas
	establecidas en la Convención de Viena sobre el Derecho de los Tratados
	en lo que dice relación con:
	+ su cumplimiento
	+ incumplimiento
	+ reparaciones
	+ entrada en vigencia
	+ reservas
	+ denuncia
	+ interpretación

	Toda vez que se viole alguno de los derechos establecido en la CADH
	implica necesariamente que se ha infringido también el art. 1.1 (Corte
	IDH) deberes de respeto y garantía

    - Obligación de Respetar los derechos y libertades

	tiene un carácter negativo, se trata de  el deber del Eº de
	**abstenerse** de realizar cualquier tipo de acción que vulnere o
	menoscabe alguno de los derechos consagrados en la CADH. Se trata de
	esferas individuales que el Eº no puede vulnerar o en los que sólo
	puede penetrar limitadamente.

	Está direccionado tanto a los Eº como a los individuos o entidades no
	estatales.

    - Obligación de Proteger

	Está dirigido principalmente al Eº y exige que proteja a los individuos
	en contra de acciones u omisiones de terceros, hoy en día con el avance
	del DIDH y la doctrina del efecto horizontal, se ha justificado la
	existencia de deberes de protección que recae sobre entidades no
	estatales, como organizaciones internacionales o corporaciones
	trasnacionales, véase Derechos Humanos y Empresas

    - Obligación de Garantizar

	Deber de los Eº en organizar todo el aparato gubernamental y en general
	todas las estructuras a través de las cuales se manifiestan el
	ejercicio del poder público  de manera tal que sean capaces de
	**asegurar jurídicamente** el libre y pleno ejercicio de los derechos
	humanos, implica una conducta gubernamental que **asegure la
	existencia, en la realidad**, de una eficaz garantía del libre y pleno
	ejercicio de los derechos

	OC 11 (Corte IDH) obligación del Eº de tomar las medidas necesarias
	para remover los obstáculos que puedan existir para que los individuos
	puedan disfrutar de los derechos. Comprende, por lo tanto, los deberes
	de prevención, investigación, sanción y reparación

	- Deber de Prevenir

	    abarca todas aquellas medidas de carácter jurídico, político,
	    administrativo y cultural que promuevan la salvaguarda de los
	    derechos humanos y que aseguren que las eventuales violaciones a
	    los mismos sean efectivamente consideradas y tratadas como un hecho
	    ilícito que, como tal, es susceptible de acarrear sanciones para
	    quienes las cometa, así como la obligación de indemnizar a las
	    víctimas por sus consecuencias perjudiciales. Estas medidas varían
	    según el derecho que se trate y según las condiciones propias de
	    cada Eº. Se trata de una obligación de carácter de medio o
	    comportamiento y no se demuestra su incumplimiento por el mero
	    hecho de que se produzca la violación de un derecho

	- Deber de Investigar

	    También se trata de una obligación de medio o comportamiento (y no
	    de resultado), pero que debe emprenderse con seriedad y no como una
	    mera formalidad condenada de antemano a ser infructuosa. Debe tener
	    sentido y ser asumida por el Eº como un deber jurídico propio y no
	    como una gestión entre particulares ( que dependa de la iniciativa
	    procesal de la víctima o de sus familiares o de la aportación
	    privada de elementos probatorios, sin que la autoridad pública
	    busque efectivamente la verdad).

	    El Eº tiene el deber de investigar a fondo las presuntas
	    violaciones en particular las desapariciones forzadas y violaciones
	    de derecho a la vida y encausar penalmente, juzgar y castigar. Debe
	    llevarse a cabo aún cuando no logren identificar los culpables. El
	    Eº está obligado a investigar los hechos inclusive cuando se deba a
	    las dificultades del ordenamiento jurídico interno impidiesen
	    identificar a los individuos responsables por los delitos de esta
	    naturaleza, subsiste el derecho de los familiares de las víctimas a
	    conocer el  destino de las víctimas, es decir, de satisfacer las
	    justas expectativas por los medios a su alcance.

	    La Corte IDH puede ordenar al Eº, como parte de las reparaciones,
	    que se investigue los hechos, aun cuando el caso ya se encuentre
	    cerrado. Está relacionado con el derecho a  la verdad.

	- Deber de Sancionar

	    la falta en su conjunto de investigación, persecución, captura,
	    enjuiciamiento y condena de los responsables. Los Eº generalmente
	    no tienen mayor interés en castigar a sus agentes, quienes
	    precisamente han cometido las violaciones a los derechos humanos en
	    nombre de aquel.

	    La impunidad puede ser parcial cuando solo se ha sancionado a un
	    grupo de ellos, como p. ej. los autores materiales de más bajo
	    rango.

	    son inadmisibles las disposiciones de amnistía, prescripción y el
	    establecimiento de excluyentes de responsabilidad que pretendan
	    impedir la investigación y sanción

	    tampoco se permite las dilaciones excesivas en los procesos.

	    también se trata de una obligación de medio o comportamiento y no
	    de resultado

	- Deber de Reparar

	    Todo Eº debe responder por las consecuencias del incumplimiento de
	    la misma. Es una consecuencia lógica de una plena garantía de
	    derechos.

	    art. 63.1 la Corte IDH dispondrá que se garantice al lesionado en
	    el goce de su derecho. Dispondrá, asimismo, si ello fuera
	    procedente que se reparen las consecuencias de la medida o
	    situación que ha configurado la vulneración de esos derechos y el
	    pago de una justa indemnización  a la parte lesionada.

	    debe ser plena, la cual consiste en el restablecimiento de la
	    situación anterior a la violación.

	    de no ser posible la Corte IDH ordenará que se adopten medidas para
	    que, además de garantizar el respeto de los derechos conculcados,
	    que se reparen las consecuencias que produjeren las infracciones y
	    se efectúe el pago de una indemnización como compensación de los
	    daños. Esta reparación no puede ser modificada o incumplida por el
	    Eº invocando disposiciones de su derecho interno.

	    se añade las medidas de carácter positivo que el Eº debe adoptar
	    para asegurar que no se repitan los hechos

	    - indemnización pecuniarias
		- daño material

		    busca compensar las consecuencias patrimoniales de las
		    violaciones declaradas en la sentencia, como el lucro
		    cesante, daño emergente, daño patrimonial familiar

		- daño inmaterial

		    daños lesivos de los hechos que no tienen carácter
		    económico o patrimonial. Sufrimientos, aflicciones a la
		    víctima y allegados, menoscabo de valores muy
		    significativos para las personas. son ej. de reparación a
		    este daño: la sentencia, indemnizaciones y gastos de
		    atención médica

	    - otras formas de reparación

		no tienen el carácter económico o patrimonial, y que se reparan
		mediante la realización de actos del poder público, como la
		investigación y sanción de los responsables, reivindiquen la
		memoria de la víctima y signifiquen reprobación oficial de las
		violaciones de los derechos humanos acaecidas con un compromiso
		de que no vuelvan a ocurrir. Puede involucrar restitución,
		rehabilitación y medidas de satisfacción como lo son las
		disculpas públicas, monumentos, garantías de no repetición,
		cambios de leyes y prácticas

		son ej. investigación y sanción, garantía de no repetición,
		adecuación normativa, oº de efectuar búsqueda seria de los
		restos, edificación de un monumento, acto público, tratamiento
		médico y psicológico, publicación de la sentencia, dar
		oficialmente el nombre de la víctima a alguna institución,
		establecer programas de educación, proporcionar un lugar para
		enterrar, adopción de medidas de formación

	    - costas y gastos

		procede solo en el caso de que el Eº pierda el caso, si gana no
		se condenará al peticionario ni a la presunta víctima tampoco.

	- Deber de no Repetición

	    en virtud de los deberes generales de respetar y adoptar
	    disposiciones de derecho interno, tiene el debe de adoptar las
	    medidas necesarias para asegurar que las violaciones declaradas en
	    una sentencia no se produzcan de nuevo en la jurisdicción del Eº.
	    Es una especie de reparación erga omnes, este deber se desprende de
	    la oº de garantizar, por lo que el Eº debe tomar por iniciativa
	    propia todas aquellas medidas necesarias para los hechos
	    violatorios no se vuelvan a repetir

    - Deber general de promoción

	implica la proactividad estatal en la difusión de los derechos y la
	educación necesaria para que los primeros interesados en su protección
	sean los propios titulares, se relaciona con la idea de que en último
	término son los propios ciudadanos quienes tienen la oº de modificar o
	reorganizar la institucionalidad estatal para respetar y proteger de
	mejor manera los derechos fundamentales

- posición de garante como modificador de la responsabilidad

    Las obligaciones antes señaladas se ven acrecentadas cuando el Eº está en
    posición de garante respecto a una persona. Se invierte la carga de la
    prueba

- deber de adecuar el derecho interno

    art.2 CADH implica la adopción de medidas en dos vertientes:

    - supresión de normas y prácticas de cualquier naturaleza que entrañen
      violación a las garantías previstas en la CADH
    - expedición de normas y desarrollo de prácticas conducentes a la efectiva
      observancia de dichas garantías

    El Eº puede violar la CADH omitiendo dictar las normas a que está obligado
    (art. 2), como también dictando normas contrarias a lo dispuesto por dicho
    tratado

    violación en abstracto = caso de que la ley no sea de aplicación inmediata
    constituye una violación.

    la Corte IDH puede ordenar que se adopten las medidas  legislativas,
    administrativas y de cualquier otro carácter que sean necesarias.

# 7. Historia de los DD.HH.

- Carta Magna 1215
- Petición de Derechos 1628
- Juicio a Carlos I
- Declaración de Independencia  EUA
- Constitución de los EUA 1787
- Carta de Derechos 1791
- Declaración de los Derechos del hombre y del Ciudadano 1789
- Declaración de la mujer y las ciudadanas 1789
- Independencia de Santo Domingo y Haití 1801
- Primera Convención de Ginebra 1864
- Constitución Mexicana 1917
- Advenimiento de la URSS 1917
- Instauración de la República Socialista de Weimar 1918
- Sociedad de las Naciones 1919
- Acuerdo de Yakta 1945
- Creación de la ONU 1945
- TRB de Nuremberg

# 8. Historia de los DD.HH. Propiamente Tales

# 9. Principales Instrumentos Jurídicos de DD.HH.

- Resolución de Ayuda al Desarrollo

	En mayo de 1972, en el marco de una conferencia sobre el comercio y el
	desarrollo las NU adoptaron en RES. 61 el objetivo de destinar el 0,7%
	del PIB de los países industrializados a *Ayuda Oficial al desarrollo
	para los países empobrecidos del Sur

- Convención Contra la Tortura, Tratos o Penas Crueles, Inhumanos o Degradantes


- Derecho a la Verdad

	Tiene su origen en el DIH como aquél derecho que tienen los familiares
	a conocer la suerte de las víctimas, y en la obligación de las partes
	en conflictos armados de buscar a los desaparecidos.  Forma parte de
	dicho derecho por estar sancionado expresamente en el art. 32 del
	Protocolo Adicional a los Convenios de Ginebra de 1949. Sin embargo, si
	bien en un principio sólo hizo referencia a las desapariciones
	forzadas, el derecho a la verdad se ha ampliado progresivamente a otras
	violaciones graves a los derechos humanos como las ejecuciones
	extrajudiciales y la tortura.  Más recientemente ha sido vinculado con
	la lucha contra la impunidad, y también con el deber de los Estados de
	realizar investigaciones eficaces de las violaciones graves de los
	derechos humanos y el derecho a un recurso judicial efectivo.  Para la
	CIDH este derecho se deriva fundamentalmente del deber general de los
	Estados de respetar y garantizar los derechos humanos, el derecho a ser
	oído por un tribunal competente, independiente e imparcial, el derecho
	a un recurso efectivo y la protección judicial y el derecho a solicitar
	información.  La Corte IDH considera que dicho derecho, no se limita a
	los casos de desaparición forzada sino que se aplica a cualquier tipo
	de violación manifiesta de los derechos humanos. Este derecho se
	aplica a todas las violaciones manifiestas de los derechos humanos y a
	las infracciones graves del derecho internacional humanitario.  Para
	más información, revisar el documento de juristas colombianos sobre el
	derecho a la verdad.

- Declaración sobre el Derecho al Desarrollo

	El desarrollo es un proceso global económico, social, cultural y
	político que tiende al mejoramiento constante del bienestar de toda la
	población y de todos los individuos sobre la base de su participación
	activa, libre y significativa en el desarrollo y en la distribución
	justa de los beneficios que de él derivan.  Se encuentra vinculado con
	el derecho de los pueblos a la libre determinación, con la cual pueden
	determinar libremente su condición política y a realizar su desarrollo
	económico, social y cultural.  El art. 1 de la Declaración sobre el
	Derechos al Desarrollo lo define como un derecho humano inalienable en
	virtud del cual todo ser humano y todos los pueblos están facultados
	para participar en un desarrollo económico, social cultural y político
	en el que puedan realizarse plenamente todos los derechos humanos y
	libertades fundamentales, a contribuir a ese desarrollo y a disfrutar
	de él.

- Convenio 169 de la OIT, 1989

	Se trata de la única convención vigente con la mirada puesta
	específicamente en los derechos pueblos indígenas con especial atención
	a la igualdad y el combate a la discriminación.  En el ámbito de la
	aplicación ha servido de guía hermenéutico para la interpretación de
	los demás derechos humanos, como en el caso Sarayaku vs. Ecuador, país
	el cual no había ratificado dicho tratado. En este caso la Corte IDH
	tomó en consideración el Convenio 169 para interpretar y dimensionar
	las obligaciones del Estado frente a la Convención Americana.  Parte de
	la base de la universalidad de los derechos humanos, por lo que los
	pueblos indígenas deben gozar plenamente de los derechos y libertades
	fundamentales sin obstáculos o discriminación, exigiendo que los
	Estados adopten medidas especiales que sean necesarias para
	salvaguardar sus derechos. Buscando el empoderamiento de los pueblos
	indígenas, respetando su derecho a elegir sus prioridades respecto al
	proceso de desarrollo, conforme a sus intereses y de controlar, cuando
	pueda, su propio desarrollo económico, social y cultural.  Los Estados
	al momento de aplicar la legislación nacional contra pueblos indígenas
	deben tener la debida consideración de sus costumbres o su derecho
	consuetudinario, tratando de compatibilizar las reglas indígenas con la
	de los derechos humanos, incluso respecto a la materia penal en lo que
	podría ser una posible afectación al principio de non bis in ídem.  Sin
	embargo se les limita en cuanto a la interpretación de pueblos, el cual
	no debe ser entendido en el mismo sentido de se es aplicada esa palabra
	en otros tratados internacionales como en los PIDCP y PIDESC, en los
	cuales se les reconoce el derecho a la autodeterminación, lo que podría
	devengar una disputa territorial entre los pueblos indígenas y los
	Estados, al serles reconocido un eventual derecho de secesión.  Por
	último, este tratado tiene un mecanismo que dificulta la denuncia por
	parte de un Estado, estableciendo una prohibición a ella por un período
	de 10 años, pudiendo hacer la denuncia durante ese año y si no lo hace
	deberá esperar 10 años nuevamente y así sucesivamente.

- Declaración de las Naciones Unidas sobre los Derechos de los Pueblos
  Indígenas

	Compone la llamada soft law primaria del Derecho Internacional, ya que
	sus normas no son vinculantes a los Estados pero pueden llegar a servir
	de base de costumbre internacional y para auxiliar la interpretación de
	normas internacionales vinculantes.  Reconoce el derecho de los pueblos
	indígenas a su libre determinación, entendiéndose por tal, aquella que
	los permite establecer su condición política y su desarrollo económico,
	social y cultural, teniendo autonomía respecto a las cuestiones
	locales.  También les reconoce el derecho al consentimiento previo e
	informado respecto a medidas legislativas y administrativas que les
	pueda afectar.

- Declaración sobre la Protección de Todas las Personas contra la Desaparición
  Forzadas o Involuntarias

	Este instrumento internacional tiene como antecedentes:

	+ Res. 33/173 del 78 informes procedentes de diversas partes del mundo
	  Res. 33/173 del 78 informes procedentes de diversas partes del mundo.
	+ Los Convenios de Ginebra del 49 y los Protocolos Adicionales del 77.
	+ La DUDH y el PIDCP.
	+ Convención contra la Tortura y otros Tratos Crueles Inhumanos y
	  degradantes.
	+ Código de Conducta para Funcionarios Encargados de Hacer Cumplir la
	  Ley.
	+ Los Principios Básicos sobre el Empleo de la Fuerza y de Armas de
	  Fuego.
	+ Declaración sobre los Principios Fundamentales de Justicia para las
	  Víctimas de Delitos y Abuso de Poder.
	+ Las Reglas Mínimas para el Tratamiento de Reclusos.
	+ Res. 47/173 del 88.
	+ ECOSOC res. 1989/65, Res. 44/162.

- Convención Internacional para la Protección de Todas las Personas contra las
  Desapariciones Forzadas.

	Tomando en consideración la Declaración anterior define la desaparición
	forzada como: el arresto, la detención, el secuestro o cualquier otra
	forma de privación de libertad, cometida por agentes del Estado o por
	partes o grupos de personas que actúan con la autorización, el apoyo o
	la aquiescencia del Estado, seguida de la negativa a reconocer dicha
	privación de libertad o del ocultamiento de la suerte o del paradero de
	la persona desaparecida, sustrayéndola a la protección de la ley.

- Declaración y Programa de Acción de Viena 93

	Su primer aporte es en materia de derechos de los pueblos al reconocer
	su libre determinación, de manera tal que pueden elegir libremente su
	estatuto político y perseguir libremente su desarrollo económico,
	social y cultural. Por lo que la Declaración reconoce el derecho de los
	pueblos bajo dominio colonial o ocupación extranjera a emprender todo
	tipo de acción legítima en conformidad con la Carta de las Naciones.
	Define democracia, el desarrollo y la protección a los derechos humanos
	como conceptos que son interdependientes y que se refuerzan mutuamente.
	Que la democracia se basa en la voluntad del pueblo, libremente
	expresada, para determinar su propio régimen político, económico,
	social y cultural y en su plena participación en todos los aspectos de
	la vida.  Hace un llamado a la comunidad internacional a apoyar a los
	países menos adelantados en su transición a la democracia y su
	desarrollo económico.  Se reafirma el derecho al desarrollo como
	derecho humano inalienable el cual se debe satisfacer de forma
	equitativa las necesidades del desarrollo y medio ambientales de las
	generaciones presentes y futuras.  Reafirma expresamente los derechos
	humanos de las mujeres y niñas estableciendo como objetivo prioritario
	de la comunidad internacional los esfuerzos para eliminar la
	discriminación.  Se destaca también la importancia instar a los Estados
	la tarea de promover y proteger los derechos de las minorías, de los
	grupos vulnerables, como de los trabajadores migrantes y de los pueblos
	indígenas. Como también en la eficacia de los derechos de los niños y
	de las personas con discapacidad, incluyendo su participación en todos
	los aspectos de la vida en sociedad.  Si bien este documento no
	contiene acciones vinculantes, impulsa a los Estados a diseñar un plan
	de acción con el fin de identificar las distintas iniciativas de
	política pública en favor de la promoción y protección de los derechos
	humanos Tener atención con lo que señala el acapice "E" de la segunda
	parte (programa de acción) que trata sobre la aplicación y mecanismo de
	vigilancia, punto 83 "refuercen los órganos de la sociedad, las
	estructuras y las instituciones nacionales que desempeñan una función
	en la promoción y salvaguardia de los derechos humanos.

- Cumbre Mundial sobre el Desarrollo Social, Implementación y Seguimiento de
  los Acuerdos de la Cumbre Social - Post Ginebra 1995, 2000.

	Se centró expresamente al derecho al desarrollo como un derecho humano
	con el propósito de situar al humano en el centro del desarrollo y de
	colocar la economía a servicio de la persona. Aportó para el concepto
	de pobreza, la falta de acceso a los servicios básicos, la falta de
	seguridad y la exclusión de la participación en la vida de la
	comunidad. Estableciendo como rasgos significativos de la pobreza la
	discriminación y la desigualdad social, por lo que la reducción de la
	pobreza está explícitamente vinculada a la reducción de la desigualdad.
	Estableció una lista de 10 compromisos para el desarrollo humano
	sostenible:
	+ Crear un entorno propicio para el desarrollo social
	+ Erradicar la pobreza en el mundo
	+ Promover el pleno empleo
	+ Promover la integración social
	+ Lograr la igualdad y equidad entre la mujer y el hombre
	+ Acceso universal y equitativo a una educación de calidad y la
	  atención primaria de la salud
	+ Acelerar el desarrollo en África y en los países menos adelantados
	+ Velar por que los programas de ajuste estructural incluyan objetivos
	  de desarrollo social
	+ Aumentar y utilizar con mayor eficacia los recursos asignados al
	  desarrollo social
	+ Fortalecer la cooperación internacional, regional y subregional para
	  el desarrollo social

- La Corte Penal Internacional

	Tiene su origen en el art. 227 del Tratado de Versalles que prevía un
	Tribunal especial con jueces de las potencias vencedoras para juzgar al
	Kaiser Guillermo de Alemania, con el cual se rompió el paradigma del
	Derecho Internacional de que el juzgamiento penal de una persona
	correspondía exclusivamente a una atribución de los Estados.  La Liga
	de las Naciones también trató de establecer un Tribunal internacional
	para el juzgamiento del delito de terrorismo en 1937, el cual solamente
	tuvo una ratificación.  Finalmente en 1945 en Londres se estableció el
	Tribunal Internacional Militar, con sede en Berlín, el conocido al día
	de hoy como el Tribunal de Nuremberg. El fundamento de su jurisdicción
	es resultado del *derecho consuetudinario* de castigo a aquellos que
	cometan crímenes contra los *valores esenciales de la comunidad
	internacional*.  Finalmente en 1945 en Londres se estableció el
	Tribunal Internacional Militar, con sede en Berlín, el conocido al día
	de hoy como el Tribunal de Nuremberg. El fundamento de su jurisdicción
	es resultado del *derecho consuetudinario* de castigo a aquellos que
	cometan crímenes contra los *valores esenciales de la comunidad
	internacional*.  Finalmente en 1945 en Londres se estableció el
	Tribunal Internacional Militar, con sede en Berlín, el conocido al día
	de hoy como el Tribunal de Nuremberg. El fundamento de su jurisdicción
	es resultado del *derecho consuetudinario* de castigo a aquellos que
	cometan crímenes contra los *valores esenciales de la comunidad
	internacional*.  Luego en 1947, la Comisión de Derecho Internacional de
	la ONU aprobó los **principios de Nuremberg**:
	+ todos los que cometan crimen internacional es capaz de castigo
	+ la ley nacional que no considere el hecho como crimen es irrelevante
	+ las inmunidades nacionales son irrelevantes
	+ la obediencia a las órdenes superiores no son eximentes
	+ todos los acusados tienen derecho a un debido proceso legal
	+ son crímenes internacionales los juzgados en Nuremberg
	+ la conspiración para cometer dichos delitos es crimen.

	El segundo Tribunal Internacional de la historia fue el *Tribunal
	Internacional Militar para el Extremo Oriente*, 1946.  Al terminar la
	guerra fría se crearon dos tribunales internacionales penales ad hoc y
	temporales, por parte del Consejo de Seguridad de la ONU.  En 1993 el
	Tribunal Penal Internacional para los crímenes contra el Derecho
	Humanitario cometidos en la ex Yuguslavia y en 1994 el Tribunal Penal
	Internacional para los crímenes ocurridos en Ruanda.  Estos tribunales
	son importantes porque codificaron los elementos de crímenes
	internacionales, como el genocidio, crímenes contra la humanidad  y
	crímenes de guerra, relacionándolos con el debido proceso legal y el
	derecho a la defensa. Adpotaron el principio de la primacia de la
	jurisdicción internacional por sobre la jurisdicción nacional, por la
	desconfianza contra las instituciones locales.  Ambos tribunales
	estaban vinculados en su estructura, ya que la Fiscalía del TPIY
	también actuaba como órgano acusatorio en el TPIR, y los jueces que
	componían la Camara de Apelación del TPIY, eran también del TPIR.  La
	CPI es un tribunal independiente de la ONU, lo que la diferencia de los
	anteriores tribunales ad hoc, pero posee una relación de cooperación
	con ella, enviando informes anuales a la Asamblea General y recibiendo
	determinadas ordenes del Consejo de Seguridad respecto al inicio o
	suspención de un trámite.  Respecto a la materia entregada a su
	jurisdicción, está limitada a los delitos de *ius cogens*, los cuales
	consisten en crímenes que ofenden los valores de la comunidad
	internacional, se entiende por tales:
	+ genocidio
	+ crímenes contra la humaidad
	+ crímenes de guerra
	+ crímenes de agresión (acordado en 2010, Kampala, Uganda)

	Respecto al territorio:
	+ cometido en territorio de un Estado Parte
	+ por un nacional del Estado Parte
	+ por declaración específica de un Estado no Parte
	+ por resolución del CS adjudicando el caso a la CPI

	Este tribunal además opera por el principio de la complementaridad
	(diferenciándose de los anteriores tribunales ad hoc, que operaban por
	el principio de la primacía), la imprescriptibilidad y de la no
	admisión de inmunidad.

## Referencias a la Ayuda Humanitaria
+ Declaración y Programa de Acción de Viena, reafirma el derecho de
  buscar refugio contra persecuciones y la obtención de soluciones
  duraderas y la prestación de ayuda humanitaria a las víctimas de
  cualquier tipo de catastrofe natural o humana.
+ Convención de los Derechos del Niño

## Convención sobre el Estatuto de los Refugiados, 1951 Definición de
refugiado: persona que es perseguida o tiene fundado temor de persecusión, por
motivos de raza, religión, nacionalidad, grupo social u opiniones políticas y
se encuentra fuera del país de su nacionalidad o residencia, y que no puede o
no quiere volver a ese país en virtud de persecución o fundado temor de
persecución.


# 10. Mecanismos Nacionales de Protección de los DD.HH.  ## Mecanismos Político
Institucionales Chile se obliga a través de todas las autoridades a hacer
respetar, promover, cumplir y exigir el respeto a los derechos humanos.

- La Subsecretaría de Derechos Humanos, Ministerio de Justicia y DDHH
  Tiene por funcion:
+ prestar asesoría y colaboración directa al Ministro de Justicia en el
  diseño y elaboración de las políticas, planes y programas relativos a
  la promoción y protección de los derechos humanos.
+ promover la elaboración de políticas, planes y programas en materia
  de derechos humanos en los organos del Estado
+ elaborar y proponer el Plan Nacional de Derechos Humanos, presentarlo
  al Comite Interministerial, coordinar su seguimiento y evaluación
+ asistir al Ministro de Justicia en el estudio crítico del derecho
  interno para proponer al Presidente las reformas pertinentes para
  adecuar su contenido a los tratados internacionales
+ prestar asesoría al Ministerio de Relaciones Exteriores ante los
  tribunales u organismos internacionales y en el seguimiento de
  informes y resoluciones
+ diseñar, fomentar, y coordinar programas de capacitación y promoción
  de los derechos humanos para funcionarios de la administración del
  Estado
+ generar instancias de participación con la sociedad civil
+ secretaria ejecutiva del Comite Interministerial de DD.HH.
+ celebrar convenios con organismos públicos, privados, nacionales e
  internacionales

- Comité Interministerial de DD.HH.  Su funcion es asesorar al
  Presidente en la determinación de los lineamientos de la política
  intersectorial del gobierno en materia de derechos humanos,
  constituyendo una instancia de información, orientación, coordinación
  y acuerdo para los ministerios y servicios que lo integran.



- Plan Nacional de Derechos Humanos Tiene una duración de 4 años y
  contiene el diseño e implementación de las políticas encaminadas al
  respeto, promoción, y protección de los derechos humanos,
  estableciendo metas, identificando responsables, recursos, mecanismos
  de seguimiento y evaluación de resultados.  Es elaborado a partir de
  las prioridades sectoriales, intersectoriales, y de política exterior
  propuestas por el Comite Interministerial de DD.HH. y en su formación
  deberá tener en consideración:
+ la opinión civil
+ informes, propuestas, recomendaciones conforme sea pertinente, del
  INDH, SIDH y el SUDH.  Abordando al menos especialmente las
  siguientes materias:
+ la promoción de la investigación, sanción y reparación de los
  crímenes de lesa humanidad y genocidios, y crímenes y delitos de
  guerra
+ la preservación de la memoria historica de las violaciones de los
  derechos humanos
+ la promoción de la no discriminación arbitrária
+ la promoción de la educación y formación en derechos humanos tanto
  respecto a la sociedad civil como en autoridades.
+ la promoción del cumplimiento de las sentencias internacionales en
  que sea parte Chile tanto del SIDH como del SUDH.



# 11. Normas de Debido Proceso

# 12. Derecho Internacional de los DD.HH.

- Concepto Es un conjunto de normas jurídicas y de principios fundamentales que
  nacieron como consecuencia de la limitación de la soberanía de los gobiernos
  en favor de las prerrogativas de la humanidad.  Está conformado por una serie
  de tratados, organismos y medidas de nivel internacional destinados a la
  protección global o regional de las personas.

- Fuentes
	+ tratados, declaraciones, pactos y resoluciones internacionales
	+ sentencias y medidas preventivas o de solución mediada de conflictos
	  de los órganos internacionales de protección
	+ principios de derecho internacional de DD.HH., especialmente *ius
	  cogens* y principio *erga omnes*
	+ derecho consuetudinario y de los pueblos
	+ teorías y doctrinas en DD.HH.
	+ acciones y políticas de ONG o movimientos globales



# 13. Sistemas de Protección

- Clasificación

	+ nacionales, internacionales, regionales
	+ judiciales, administrativos, mixtos
	+ de derechos humanos y de derecho humanitario


# 14. Naciones Unidas, Relatores e Interpelaciones

- Procedimientos de Denuncias

	Son mecanismos a través de los cuales se someten los casos de presuntas
	violaciones de los derechos humanos a la consideración de la ONU. Son
	tres:

	+ Denuncias de los particulares en virtud de los **tratados
	  internacionales de DD.HH.**
	+ Escritos de los particulares conforme a los **relatores especiales
	  del Consejo de DD.HH.**
	+ Procedimiento de **denuncias del Consejo de DD.HH.**

	En el caso de los procedimientos especiales, como es el caso de los
	relatores especiales (2da hipotesis), las denuncias son admitidas con
	independencia de que el Estado haya ratificado los correspondientes
	tratados internacionales.

- Mecanismos de Derechos Humanos

	Son órganos que **vigilan y cooperan** con el cumplimiento de las
	obligaciones y compromisos aceptados por los países miembros de las NU
	derivados de tratados y otros instrumentos internacionales de derechos
	humanos.  Se dividen en dos categorias:
	+ órganos basados en la Carta de la ONU
	+ órganos creados en virtud de tratados internacionales de derechos
	  humanos

	Integran como mecanismos basados en la Carta de las NU:
	+ Consejo de DD.HH.
	+ Examen Periódico Universal
	+ Procedimientos Especiales

	Integran como órganos creados en virtud de tratados:
	+ Comité de DD.HH.
	+ Comité de DESC
	+ Comité para la Eliminación de la Discriminación Racial
	+ Comité para la Eliminación de la Discriminación contra la Mujer
	+ Comité contra la Tortura y el Protocolo Facultativo de la Convención
	  Contra la Tortura
	+ Comité de los Derechos del Niño
	+ Comité para la Protección de los derechos de todos los Trabajadores
	  Migratorios y de sus Familiares
	+ Comité sobre los derechos de las Personas con Discapacidad
	+ Comité sobre la Protección de todas las Personas contra las
	  Desapariciones Forzadas


- La Oficina del Alto Comisionado para los DD.HH. (ACNUDH)

	Es el organismo encargado de la promoción y protección. Realiza
	declaraciones acerca de la situación de las garantías básicas en el
	mundo y tiene autoridad para investigar situaciones irregulares y
	elaborar informes sobre ellas.  Además de su mandato de promover y
	proteger los derechos humanos, el Alto Comisionado para los DD.HH.
	proporciona servicios de secretaría técnica, asesorando y apoyando   a
	estos mecanismos de supervisión y vigilancia de los derechos humanos en
	el SUDH.


- Consejo de DD.HH.

	Establecido el año 2006, sustituye a la Comisión de DD.HH.  Es un
	órgano intergubernamental que consiste en un foro mundial de discusión
	que reúne en Ginebra durante al menos 10 semanas al año. Sus
	principales funciones incluyen la de analizar violaciones graves y
	sistemáticas de DD.HH. y desarrollar el derecho internacional de los
	derechos humanos.  Tiene la facultad de realizar Procedimientos
	Especiales, los cuales son llevados a cabo por expertos independientes
	y destacados que trabajan de manera voluntaria, examinando,
	supervisando e informando públicamente, y asesoran desde una
	perspectiva temática o por país.  Además, cuenta con un procedimiento
	de denuncias que sirve para abordar cuadros persistentes de violaciones
	en cualquier parte del mundo.  Cuenta con la asesoría de otros órganos:
	+ Comité Asesor
	+ Grupo de Trabajo sobre el derecho al desarrollo
	+ Mecanismo de Expertos sobre los derechos de los pueblos indígenas
	+ Foro sobre Cuestiones de las Minorías.

- Examen Periódico Universal

	Fue creado en marzo de 2006 por la misma resolución que creó el
	Consejo.  En él, se involucra la revisión del cumplimiento de las
	obligaciones y compromisos en derechos humanos de cada uno de los 192
	Estados Miembros de las NU cada 4 años.  Se desarrolla de la siguiente
	manera:
	+ información que prepara el Estado
	+ recopilación de información presentada por el Alto Comisionado,
	  basada en los procedimientos especiales, órganos de tratados y otras
	  entidades
	+ resumen que prepara el Alto Comisionado sobre información que envían
	  las ONG, instituciones nacionales de derechos humanos y otros
	  interesados.

	Busca ser un mecanismo de cooperación basado en el diálogo interactivo
	con el Estado examinado.

- Los Procedimientos Especiales

	Se trata de los mecanismos establecidos por la antigua Comisión de
	Derechos Humanos para abordar situaciones específicas en los países o
	cuestiones temáticas en todo el mundo.  Puede ser un Relator o Experto
	independiente o de un Grupo de Trabajo.  Tienen la función de examinar,
	supervisar, asesorar e informar públicamente acerca de situaciones de
	derechos humanos en países o territorios específicos, conocidos como
	mandatos por país, o sobre temas específicos (mandato temático)

- El Asesor Especial para la Prevención del Genocidio

	Actúa como catalizador para propiciar la toma de conciencia sobre las
	causas sobre las causas y dinámica del genocidio, alertar a los agentes
	pertinentes de la existencia de un riesgo de genocidio, y realizar
	actividades de promoción y movilización para que se puedan adoptar las
	medidas apropiadas.  Tiene como responsabilidad:
	+ reunir información que exista sobre infracciones graves y masivas de
	  los derechos humanos que tengan origen étnico o racial y que, de no
	  ser prevenidas o detenidas, podrían culminar en genocidio
	+ servirá de mecanismo de alerta temprana al Secretario General y, por
	  su conducto, al Consejo de Seguridad, al señalar a su atención
	  situaciones que podrían culminar en genocidio
	+ hacer recomendaciones al Consejo de Seguridad, por conducto del
	  Secretario General, sobre medidas para prevenir o detener el
	  genocidio
	+ hacer de enlace con el sistema de las NU respecto de actividades para
	  prevenir el genocidio y tratar de aumentar la capacidad de las NU
	  para analizar y manejar información relativa al genocidio y a
	  crímenes conexos.




# 15. Sistema Interamericano de los DD.HH.

- La Comisión IDH

	Es un órgano principal y autónomo de la OEA creado en 1959, cuyo
	mandato surge de la Carta de la OEA, está integrada por 7 miembros que
	no representan a ningún país y que son elegidos por la Asamblea General
	de la OEA.  Tiene por función principal promover la observancia y la
	defensa de los derechos humanos en las Américas. Esta función la
	realiza a través de:

	+ visitas a los países
	+ actividades o iniciativas temáticas
	+ preparación de informes sobre la situación de los DD.HH. en un país o
	  sobre un tema en especial
	+ adopción de medidas cautelares
	+ solicitud de medidas provisionales a la Corte IDH
	+ procesamiento y análisis de peticiones individuales con el objetivo
	  de determinar la responsabilidad internacional de los Estados por
	  violaciones a los derechos humanos y emitir recomendaciones que
	  considere necesarias



# 16. Sistema Europeo de DD.HH.

# 17. Sistema Africano de DD.HH.

# 18. Responsabilidad Penal Internacional

# 19. Derecho Internacional Humanitario

El CICR (Comité Internacional de la Cruz Roja) entiende por tal, las
normas internacionales, de origen convencional o consuetudinario,
especialmente destinadas a solucionar los problemas de índole
humanitaria que se derivan directamente de los conflictos armados, ya
sean éstos internacionales o no, y limitan, por razones humanitarias,
el derecho de las partes en conflicto a utilizar los métodos y medios
de hacer la guerra.

- La Comisión Internacional de Encuesta

	Se trata de un mecanismo establecido en el art. 90 del I Protocolo
	adicional a los Convenios de Ginebra que tiene competencia para:
	+ investigar cualquier hecho que haya sido alegado como infracción
	  grave tal como se define en los Convenios de Ginebra o el el I
	  Protocolo Adicional.
	+ facilitar el retorno a una actitud de respeto a los Convenios y al I
	  Protocolo Las investigaciones son realizadas por una Sala compuesta
	  por 7 miembros, invita a las Altas Partes a comparecer y a presentar
	  pruebas, las conclusiones es presentada por la Comisión a las partes
	  con las recomendaciones que estimare oportunas, las cuales no se
	  harán publicas a menos que todas las partes así lo pidan.
